language: node_js
node_js:
  - "10"
script:
  - npm ci
  - npm run build --prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/client
  on:
    branch: master
cache: npm
